### ISSUE TITLE
doesn't sort dependencies with keys

### ISSUE THREAD

**Issue by AdrienLemaire** [danchengash/pubspec-dependency-sorter#11]
Thanks for making this package!
I keep getting the sort_pub_dependency error after running `flutter pub run pubspec_dependency_sorter`

What I expect:

```yaml
dev_dependencies: 
  build_runner: ^2.2.1
  fake_cloud_firestore: ^1.3.1
  flutter_test: 
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  pubspec_dependency_sorter: ^0.0.2
  test: ^1.14.4
  very_good_analysis: ^3.1.0
```

What I get:

![](https://i.imgur.com/7Fdt7mI.png)

Another note: It would be great if the package didn't remove inline comments, so I can keep useful documentation in the file.

**Comment by danchengash** [comment]
Thanks for the feature requests and great comments. I will work on them.
On the issue you are facing, you can manually correct the affected package before i work on the issue

**Comment by DanOxlade** [comment]
Hey, I also have the same issue, multi-line dependencies don't get sorted correctly.

Otherwise, this package is awesome!

**Comment by Yetispapa** [comment]
Any update @danchengash?

**Comment by shinriyo** [comment]
They are not sorted also.

```
flutter:
  sdk: flutter
flutter_localizations:
  sdk: flutter
```
