### ISSUE TITLE
"flutter" dependency not sorted correctly

### ISSUE THREAD

**Issue by HadenHiles** [danchengash/pubspec-dependency-sorter#15]
The dart linter is giving me a sort warning even after running `flutter pub run pubspec_dependency_sorter`. The flutter dependency seems to be listed below the rest instead of alphabetical. Is this on purpose just because it's required for flutter?

For now I'll just set `sort_pub_dependencies: false` in the `analysis_options.yaml` and call it a day.

Cheers!

![unsorted-dependencies-flutter-line](https://github.com/danchengash/pubspec-dependency-sorter/assets/5418783/75986e4f-3b28-4452-a514-0985856a23b3)
 
Full pubspec.yaml:
```
name: tenthousandshotchallenge
version: 1.1.0+17
publish_to: none
description: A flutter project for the Ten Thousand Shot Challenge app
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  auto_size_text: ^3.0.0
  charts_flutter: ^0.12.0
  chewie: ^1.3.3
  cloud_firestore: ^4.17.0
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.2
  data_connection_checker_nulls: ^0.0.2
  firebase_analytics: ^10.10.2
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  firebase_remote_config: ^4.4.2
  flutter_barcode_scanner: ^2.0.0
  flutter_cache_manager: ^3.1.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^17.0.1
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^10.7.0
  global_configuration: ^2.0.0-nullsafety.1
  google_sign_in: ^6.2.1
  html: ^0.15.0
  http: ^1.2.1
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  numberpicker: ^2.1.1
  package_info: ^2.0.2
  password_strength: ^0.2.0
  prompt_dialog: ^1.0.0
  provider: ^6.0.1
  pubspec_dependency_sorter: ^1.0.4
  qr_flutter: ^4.0.0
  settings_ui: ^2.0.1
  share_plus: ^9.0.0
  shared_preferences: ^2.0.5
  sign_in_button: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.6
  vibration: ^1.7.3
  video_player: any
  youtube_player_flutter: ^9.0.1
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter
flutter_icons: 
  android: launcher_icon
  image_path: assets/images/app-icon.png
  ios: true
flutter: 
  assets: 
    - assets/cfg/
    - assets/images/
    - assets/images/avatars/
    - assets/images/avatars/teams/
    - assets/images/avatars/players/
    - assets/images/avatars/characters/
    - assets/images/shop/
    - assets/fonts/
    - assets/animations/
  fonts: 
    - 
      family: NovecentoSans
      fonts: 
        - 
          asset: assets/fonts/novecento-sans-condensed-medium.otf
  uses-material-design: true
```
